name: Hello World Workflow

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  snyk_security_scan_sca:
    runs-on: ubuntu-latest
    name: Run the SCA scan on the source code
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonar_cloud_unit_test_sast:
    runs-on: ubuntu-latest
    needs: snyk_security_scan_sca
    name: Run unit tests and SAST scan on the source code 
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 16
        cache: npm
    - run: npm install
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=noev-dev-github-actions-nodejs-project
          -Dsonar.projectKey=noev-dev-project-github-actions-nodejs-project